---
title: "Moore (Meilleure perf par age)"
output: html_document
date: "2026-02-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(minpack.lm)
library(broom)
library(ggplot2)
library(dplyr)
```

# Moore meilleure perf par age

## Modèles de Moore

### Utile

```{r}
generate_starts <- function(max){
  start_a <- runif(1, 0.9*max, 1.2*max)
  start_b <- runif(1, 0.08, 0.1)
  start_c <- runif(1, start_a/100 - 0.25, start_a/100 + 0.25)
  start_d <- runif(1, 0.06, 0.07)
  return(list(a = start_a, b = start_b, c = start_c, d = start_d))
}

lower_bounds <- c(a = 5, b = 0.001, c = -100, d = 0.001)

n_iterations <- 1000
```


### Homme disque 

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit <- NULL
min_rmse <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf <- max(df_men_Discus_Throw$meilleure_perf)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_men_Discus_Throw,
      start = generate_starts(max_perf),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse) {
      min_rmse <- current_rmse
      best_fit <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse, "\n")
  summary(best_fit)
  params <- coef(best_fit)
  print(params)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit)

t_pic <- log(params["a"]*params["b"]/(params["c"]*params["d"]))/(params["b"]+params["d"])
print(t_pic)

# 5. Visualisation
plot(df_men_Discus_Throw$Age, df_men_Discus_Throw$meilleure_perf, main="Ajustement du modèle", pch=16)
lines(df_men_Discus_Throw$Age, predict(best_fit), col="red", lwd=2)
```

### Femme disque 

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_f_d <- NULL
min_rmse_f_d <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_f_d <- max(df_women_Discus_Throw$meilleure_perf)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result_f_d <- tryCatch({
    nlsLM(
      meilleure_perf ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_women_Discus_Throw,
      start = generate_starts(max_perf_f_d),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result_f_d)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_f_d) {
      min_rmse_f_d <- current_rmse
      best_fit_f_d <- result_f_d
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_f_d)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_f_d, "\n")
  summary(best_fit_f_d)
  params_f_d <- coef(best_fit_f_d)
  print(params_f_d)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_f_d)

t_pic_f_d <- log(params_f_d["a"]*params_f_d["b"]/(params_f_d["c"]*params_f_d["d"]))/(params_f_d["b"]+params_f_d["d"])
print(t_pic_f_d)

# 5. Visualisation
plot(df_women_Discus_Throw$Age, df_women_Discus_Throw$meilleure_perf, main="Ajustement du modèle", pch=16)
lines(df_women_Discus_Throw$Age, predict(best_fit_f_d), col="red", lwd=2)
```

### Homme Marteau 

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_h_m <- NULL
min_rmse_h_m <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_h_m <- max(df_men_Hammer_Throw$meilleure_perf)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_men_Hammer_Throw,
      start = generate_starts(max_perf_h_m),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_h_m) {
      min_rmse_h_m <- current_rmse
      best_fit_h_m <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_h_m)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_h_m, "\n")
  summary(best_fit_h_m)
  params_h_m <- coef(best_fit_h_m)
  print(params_h_m)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_h_m)

t_pic_h_m <- log(params_h_m["a"]*params_h_m["b"]/(params_h_m["c"]*params_h_m["d"]))/(params_h_m["b"]+params_h_m["d"])
print(t_pic_h_m)

# 5. Visualisation
plot(df_men_Hammer_Throw$Age, df_men_Hammer_Throw$meilleure_perf, main="Ajustement du modèle", pch=16)
lines(df_men_Hammer_Throw$Age, predict(best_fit_h_m), col="red", lwd=2)
```

### Femme Marteau 

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_f_m <- NULL
min_rmse_f_m <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_f_m <- max(df_women_Hammer_Throw$meilleure_perf)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_women_Hammer_Throw,
      start = generate_starts(max_perf_h_m),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_f_m) {
      min_rmse_f_m <- current_rmse
      best_fit_f_m <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_f_m)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_f_m, "\n")
  summary(best_fit_f_m)
  params_f_m <- coef(best_fit_f_m)
  print(params_f_m)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_f_m)

t_pic_f_m <- log(params_f_m["a"]*params_f_m["b"]/(params_f_m["c"]*params_f_m["d"]))/(params_f_m["b"]+params_f_m["d"])
print(t_pic_f_m)

# 5. Visualisation
plot(df_women_Hammer_Throw$Age, df_women_Hammer_Throw$meilleure_perf, main="Ajustement du modèle", pch=16)
lines(df_women_Hammer_Throw$Age, predict(best_fit_f_m), col="red", lwd=2)
```

### Homme Javelot

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_h_j <- NULL
min_rmse_h_j <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_h_j <- max(df_men_Javelin_Throw$meilleure_perf)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_men_Javelin_Throw,
      start = generate_starts(max_perf_h_j),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_h_j) {
      min_rmse_h_j <- current_rmse
      best_fit_h_j <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_h_j)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_h_j, "\n")
  summary(best_fit_h_j)
  params_h_j <- coef(best_fit_h_j)
  print(params_h_j)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_h_j)

t_pic_h_j <- log(params_h_j["a"]*params_h_j["b"]/(params_h_j["c"]*params_h_j["d"]))/(params_h_j["b"]+params_h_j["d"])
print(t_pic_h_j)

# 5. Visualisation
plot(df_men_Javelin_Throw$Age, df_men_Javelin_Throw$meilleure_perf, main="Ajustement du modèle", pch=16)
lines(df_men_Javelin_Throw$Age, predict(best_fit_h_j), col="red", lwd=2)
```

### Femme Javelot

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_f_j <- NULL
min_rmse_f_j <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_f_j <- max(df_women_Javelin_Throw$meilleure_perf)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_women_Javelin_Throw,
      start = generate_starts(max_perf_f_j),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_f_j) {
      min_rmse_f_j <- current_rmse
      best_fit_f_j <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_f_j)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_f_j, "\n")
  summary(best_fit_f_j)
  params_f_j <- coef(best_fit_f_j)
  print(params_f_j)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_f_j)

t_pic_f_j <- log(params_f_j["a"]*params_f_j["b"]/(params_f_j["c"]*params_f_j["d"]))/(params_f_j["b"]+params_f_j["d"])
print(t_pic_f_j)

# 5. Visualisation
plot(df_women_Javelin_Throw$Age, df_women_Javelin_Throw$meilleure_perf, main="Ajustement du modèle", pch=16)
lines(df_women_Javelin_Throw$Age, predict(best_fit_f_j), col="red", lwd=2)
```

### Homme Poids

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_h_p <- NULL
min_rmse_h_p <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_h_p <- max(df_men_Shot_Put$meilleure_perf)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_men_Shot_Put,
      start = generate_starts(max_perf_h_p),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_h_p) {
      min_rmse_h_p <- current_rmse
      best_fit_h_p <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_h_p)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_h_p, "\n")
  summary(best_fit_h_p)
  params_h_p <- coef(best_fit_h_p)
  print(params_h_p)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_h_p)

t_pic_h_p <- log(params_h_p["a"]*params_h_p["b"]/(params_h_p["c"]*params_h_p["d"]))/(params_h_p["b"]+params_h_p["d"])
print(t_pic_h_p)

# 5. Visualisation
plot(df_men_Shot_Put$Age, df_men_Shot_Put$meilleure_perf, main="Ajustement du modèle", pch=16)
lines(df_men_Shot_Put$Age, predict(best_fit_h_p), col="red", lwd=2)
```

### Femme Poids

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_f_p <- NULL
min_rmse_f_p <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_f_p <- max(df_women_Shot_Put$meilleure_perf)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_women_Shot_Put,
      start = generate_starts(max_perf_f_p),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_f_p) {
      min_rmse_f_p <- current_rmse
      best_fit_f_p <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_f_p)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_f_p, "\n")
  summary(best_fit_f_p)
  params_f_p <- coef(best_fit_f_p)
  print(params_f_p)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_f_p)

t_pic_f_p <- log(params_f_p["a"]*params_f_p["b"]/(params_f_p["c"]*params_f_p["d"]))/(params_f_p["b"]+params_f_p["d"])
print(t_pic_f_p)

# 5. Visualisation
plot(df_women_Shot_Put$Age, df_women_Shot_Put$meilleure_perf, main="Ajustement du modèle", pch=16)
lines(df_women_Shot_Put$Age, predict(best_fit_f_p), col="red", lwd=2)
```

### Homme 100 m 

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_h_100 <- NULL
min_rmse_h_100 <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_h_100 <- max(df_men_100_Metres$meilleure_perf_km_par_h)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf_km_par_h ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_men_100_Metres,
      start = generate_starts(max_perf_h_100),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_h_100) {
      min_rmse_h_100 <- current_rmse
      best_fit_h_100 <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_h_100)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_h_100, "\n")
  summary(best_fit_h_100)
  params_h_100 <- coef(best_fit_h_100)
  print(params_h_100)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```



```{r}
summary(best_fit_h_100)

t_pic_h_100 <- log(params_h_100["a"]*params_h_100["b"]/(params_h_100["c"]*params_h_100["d"]))/(params_h_100["b"]+params_h_100["d"])
print(t_pic_h_100)

# 5. Visualisation
plot(df_men_100_Metres$Age, df_men_100_Metres$meilleure_perf_km_par_h, main="Ajustement du modèle", pch=16)
lines(df_men_100_Metres$Age, predict(best_fit_h_100), col="red", lwd=2)
```

### Femme 100 m 

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_f_100 <- NULL
min_rmse_f_100 <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_f_100 <- max(df_women_100_Metres$meilleure_perf_km_par_h)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf_km_par_h ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_women_100_Metres,
      start = generate_starts(max_perf_f_100),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_f_100) {
      min_rmse_f_100 <- current_rmse
      best_fit_f_100 <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_f_100)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_f_100, "\n")
  summary(best_fit_f_100)
  params_f_100 <- coef(best_fit_f_100)
  print(params_f_100)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```


```{r}
summary(best_fit_f_100)

t_pic_f_100 <- log(params_f_100["a"]*params_f_100["b"]/(params_f_100["c"]*params_f_100["d"]))/(params_f_100["b"]+params_f_100["d"])
print(t_pic_f_100)

# 5. Visualisation
plot(df_women_100_Metres$Age, df_women_100_Metres$meilleure_perf_km_par_h, main="Ajustement du modèle", pch=16)
lines(df_women_100_Metres$Age, predict(best_fit_f_100), col="red", lwd=2)
```

### Homme 200 m 

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_h_200 <- NULL
min_rmse_h_200 <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_h_200 <- max(df_men_200_Metres$meilleure_perf_km_par_h)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf_km_par_h ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_men_200_Metres,
      start = generate_starts(max_perf_h_200),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_h_200) {
      min_rmse_h_200 <- current_rmse
      best_fit_h_200 <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_h_200)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_h_200, "\n")
  summary(best_fit_h_200)
  params_h_200 <- coef(best_fit_h_200)
  print(params_h_200)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_h_200)

t_pic_h_200 <- log(params_h_200["a"]*params_h_200["b"]/(params_h_200["c"]*params_h_200["d"]))/(params_h_200["b"]+params_h_200["d"])
print(t_pic_h_200)

# 5. Visualisation
plot(df_men_200_Metres$Age, df_men_200_Metres$meilleure_perf_km_par_h, main="Ajustement du modèle", pch=16)
lines(df_men_200_Metres$Age, predict(best_fit_h_200), col="red", lwd=2)
```

### Femme 200 m

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_f_200 <- NULL
min_rmse_f_200 <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_f_200 <- max(df_women_200_Metres$meilleure_perf_km_par_h)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf_km_par_h ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_women_200_Metres,
      start = generate_starts(max_perf_f_200),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_f_200) {
      min_rmse_f_200 <- current_rmse
      best_fit_f_200 <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_f_200)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_f_200, "\n")
  summary(best_fit_f_200)
  params_f_200 <- coef(best_fit_f_200)
  print(params_f_200)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_f_200)

t_pic_f_200 <- log(params_f_200["a"]*params_f_200["b"]/(params_f_200["c"]*params_f_200["d"]))/(params_f_200["b"]+params_f_200["d"])
print(t_pic_f_200)

# 5. Visualisation
plot(df_women_200_Metres$Age, df_women_200_Metres$meilleure_perf_km_par_h, main="Ajustement du modèle", pch=16)
lines(df_women_200_Metres$Age, predict(best_fit_f_200), col="red", lwd=2)
```

### Homme 400 m

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_h_400 <- NULL
min_rmse_h_400 <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_h_400 <- max(df_men_400_Metres$meilleure_perf_km_par_h)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf_km_par_h ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_men_400_Metres,
      start = generate_starts(max_perf_h_400),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_h_400) {
      min_rmse_h_400 <- current_rmse
      best_fit_h_400 <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_h_400)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_h_400, "\n")
  summary(best_fit_h_400)
  params_h_400 <- coef(best_fit_h_400)
  print(params_h_400)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```


```{r}
summary(best_fit_h_400)

t_pic_h_400 <- log(params_h_400["a"]*params_h_400["b"]/(params_h_400["c"]*params_h_400["d"]))/(params_h_400["b"]+params_h_400["d"])
print(t_pic_h_400)

# 5. Visualisation
plot(df_men_400_Metres$Age, df_men_400_Metres$meilleure_perf_km_par_h, main="Ajustement du modèle", pch=16)
lines(df_men_400_Metres$Age, predict(best_fit_h_400), col="red", lwd=2)
```

### Femme 400 m

```{r}
# Initialisation des variables pour stocker le meilleur résultat
best_fit_f_400 <- NULL
min_rmse_f_400 <- Inf # On commence avec une erreur infinie

# On récupère le max une seule fois pour l'efficacité
max_perf_f_400 <- max(df_women_400_Metres$meilleure_perf_km_par_h)

for (i in 1:n_iterations) {
  
  # Utilisation de tryCatch pour ignorer les erreurs de convergence
  result <- tryCatch({
    nlsLM(
      meilleure_perf_km_par_h ~ a * (1 - exp(-b * Age)) + c * (1 - exp(d * Age)),
      data = df_women_400_Metres,
      start = generate_starts(max_perf_f_400),
      lower = lower_bounds,
      control = nls.lm.control(maxiter = 1000, maxfev = 2000)
    )
  }, error = function(e) return(NULL)) # Si erreur, on retourne NULL
  
  # Si le modèle a convergé, on compare l'erreur
  if (!is.null(result)) {
    current_rmse <- summary(result)$sigma # L'erreur résiduelle standard
    
    if (current_rmse < min_rmse_f_400) {
      min_rmse_f_400 <- current_rmse
      best_fit_f_400 <- result
    }
  }
}

# --- Affichage des résultats finaux ---
if (!is.null(best_fit_f_400)) {
  cat("Meilleur modèle trouvé avec une RMSE de :", min_rmse_f_400, "\n")
  summary(best_fit_f_400)
  params_f_400 <- coef(best_fit_f_400)
  print(params_f_400)
} else {
  print("Le modèle n'a jamais convergé. Vérifiez vos bornes ou vos fonctions de départ.")
}
```

```{r}
summary(best_fit_f_400)

t_pic_f_400 <- log(params_f_400["a"]*params_f_400["b"]/(params_f_400["c"]*params_f_400["d"]))/(params_f_400["b"]+params_f_400["d"])
print(t_pic_f_400)

# 5. Visualisation
plot(df_women_400_Metres$Age, df_women_400_Metres$meilleure_perf_km_par_h, main="Ajustement du modèle", pch=16)
lines(df_women_400_Metres$Age, predict(best_fit_f_400), col="red", lwd=2)
```



